# Generated by Django 5.2.6 on 2025-09-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('timeframe', models.CharField(default='24h', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('input_payload', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
