# Generated by Django 5.2.6 on 2025-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
