def render_report_html(report_data: dict) -> str:
    """
    Generate styled HTML from the report dictionary.
    Mimics the frontend React design using inline styles.
    """
    def render_rows(obj, parent_key=""):
        html = ""
        for key, value in obj.items():
            display_key = f"{parent_key} → {key}" if parent_key else key
            if isinstance(value, dict):
                html += render_rows(value, display_key)
            else:
                html += f"""
                <div style="
                    display: flex;
                    flex-direction: row;
                    margin-bottom: 8px;
                    border-radius: 8px;
                    overflow: hidden;
                    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                ">
                    <div style="
                        background-color: #f3f3f3;
                        padding: 8px;
                        width: 30%;
                        font-weight: bold;
                        word-break: break-word;
                    ">{display_key}</div>
                    <div style="
                        background-color: #ffffff;
                        padding: 8px;
                        width: 70%;
                        word-break: break-word;
                    ">{value}</div>
                </div>
                """
        return html

    inner_html = render_rows(report_data)
    html_email = f"""
    <div style="
        font-family: Arial, sans-serif;
        background-color: #f0f2f5;
        padding: 20px;
    ">
        <div style="
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 16px;
            padding: 20px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        ">
            <h2 style="text-align:center; color:#333333;">Analysis Report</h2>
            {inner_html}
            <div style="text-align:center; margin-top:20px;">
                <small style="color:#666666;">Generated by Crypto Analysis System</small>
            </div>
        </div>
    </div>
    """
    return html_email
